name: 上传到七牛存储
on:
  push:
    branches:
      - "surge"
  pull_request:
    branches: ["surge"]

jobs:
  actions:
    name: 上传到七牛云任务
    runs-on: ubuntu-latest

    steps:
    - name: 检索文件
      uses: actions/checkout@v2
      with:
       fetch-depth: 0

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: 安装依赖包
      run: |
       pip install -r script/requirements.txt

    - name: 执行上传
      run: |
        python script/upload.py
      with:
        bucket: xee # 空间名称，按实际情况填写
        zone: 华南 # 存储区域，按实际情况填写 备注1
        access_key: ${{ secrets.QINIU_AK }} # 七牛云 AccessKey 备注2
        secret_key: ${{ secrets.QINIU_SK }} # 七牛云 SecretKey 备注2

    - name: Test printing your secret (Remove this step in production)
      run: cat $HOME/secrets/my_secret.json
#        local_dir: / # 本地文件夹
#        local_exclude: "**/.github/**, **/*.s, **/*.js, **/*.md, **/*.crt" # 要排除的内容，要符合 glob 格式
#        target_dir: / # 要上传到七牛云中的文件夹
