name: 上传到七牛存储
on:
  push:
    branches:
      - "surge"
  pull_request:
    branches: ["surge"]

jobs:
  job1:
    name: 上传到七牛云任务
    runs-on: ubuntu-latest
    steps:
    - name: 检索文件
      uses: actions/checkout@v2
      with:
       fetch-depth: 0

    - name: 执行上传
      uses: luochongfei/up2qn@master
      with:
        bucket: xee # 空间名称，按实际情况填写
        zone: 华南 # 存储区域，按实际情况填写 备注1
        access_key: ${{ secrets.QINIU_AK }} # 七牛云 AccessKey 备注2
        secret_key: ${{ secrets.QINIU_SK }} # 七牛云 SecretKey 备注2
        local_dir: / # 本地文件夹
        local_exclude: "**/.github/**, **/*.s, **/*.js, **/*.md" # 要排除的内容，要符合 glob 格式
        target_dir: / # 要上传到七牛云中的文件夹
