name: OpenWrt Debug

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Show system
        run: |
          echo "===== SYSTEM ====="
          cat /etc/os-release
          uname -a
          whoami
          df -h

      - name: Setup SSH debug session
        uses: WarpBuilds/action-debugger@v1.3
        with:
          detached: true
