name: Build OpenWrt debug

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      # ============================================================
      # 1. Checkout
      # ============================================================
      - name: Checkout
        uses: actions/checkout@v5

      # ============================================================
      # 2. Install dependencies
      # ============================================================
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y \
            build-essential \
            git \
            libncurses-dev \
            libpython3-dev \
            python3-setuptools \
            python3-pyelftools \
            swig

      # ============================================================
      # 3. Clone OpenWrt
      # ============================================================
      - name: Clone OpenWrt
        run: |
          set -eu

          git clone \
            --branch v23.05.6 \
            --depth 1 \
            https://github.com/openwrt/openwrt.git

          cd openwrt

          echo "======================================"
          echo "OpenWrt version"
          echo "======================================"

          git describe --tags --always

      # ============================================================
      # 4. Use custom firmware-utils
      #
      # firmware-utils is built from our own fork/commit.
      # ============================================================
      

      - name: Show system
        run: |
          echo "===== SYSTEM ====="
          cat /etc/os-release
          uname -a
          whoami
          df -h

      - name: Setup SSH debug session
        uses: WarpBuilds/action-debugger@v1.3
        with:
          detached: true
