name: update ali oss cloud conf
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install oss
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: replace file
      run: |
        sed -i '1s/.*/#!MANAGED-CONFIG {{ secrets.MANAGED_CONFIG_URL }}/' cloud.conf
        sed -i 's/SURGE_URL/${{ secrets.SURGE_URL }}/' cloud.conf

    - name: run with python script
      env:
        ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
        ACCESS_KEY_SECRET: ${{ secrets.ACCESS_KEY_SECRET }}
        ENDPOINT: ${{ secrets.ENDPOINT }}
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      run: python script.py
