name: update ali oss cloud conf
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: |
        python -m pip install --upgrade pip
        pip install oss2

    - name: replace file
      run: |
        sed -i '1s/.*/#!MANAGED-CONFIG ${{ secrets.MANAGED_CONFIG_URL }}/' cloud.conf
        sed -i 's/SURGE_URL/${{ secrets.SURGE_URL }}/g' cloud.conf

    - name: run with python script
      env:
        ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
        ACCESS_KEY_SECRET: ${{ secrets.ACCESS_KEY_SECRET }}
        ENDPOINT: ${{ secrets.ENDPOINT }}
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      run: python script.py
