name: 更新文件

on:
  workflow_dispatch:
  schedule:
    - cron:  '15 */7 * * *'

jobs:
  append-logs:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        ref: surge
        
    - name: Auto commit
      run: |
          git config --local user.email "fangling@outlook.com"
          git config --local user.name "caaby"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          # git pull --rebase
          echo $(TZ=UTC-8 date +%Y-%m-%d" "%H:%M:%S) >> log.txt
          git commit --allow-empty -am "change coloud config"
          git push
